# Generated by Django 5.2.8 on 2025-11-19 15:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon class from your icon font (e.g., fas fa-tshirt)', max_length=50, verbose_name='icon class')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='service name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('service_type', models.CharField(choices=[('wash_fold', 'Wash & Fold'), ('dry_clean', 'Dry Cleaning'), ('ironing', 'Ironing'), ('special', 'Special Treatment'), ('alteration', 'Alteration')], default='wash_fold', max_length=20, verbose_name='service type')),
                ('short_description', models.TextField(blank=True, max_length=255, verbose_name='short description')),
                ('description', models.TextField(blank=True, verbose_name='detailed description')),
                ('instructions', models.TextField(blank=True, verbose_name='care instructions')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base price')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='is taxable')),
                ('min_processing_duration', models.PositiveIntegerField(default=1, verbose_name='minimum processing duration')),
                ('max_processing_duration', models.PositiveIntegerField(default=3, verbose_name='maximum processing duration')),
                ('duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10, verbose_name='duration unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured service')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='service image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service FAQ',
                'verbose_name_plural': 'service FAQs',
                'ordering': ['service', 'display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (required for WCAG)', max_length=255, verbose_name='alternative text')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service image',
                'verbose_name_plural': 'service images',
                'ordering': ['service', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='option name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('option_type', models.CharField(choices=[('checkbox', 'Checkbox (Yes/No)'), ('select', 'Select from list'), ('multiselect', 'Select multiple'), ('number', 'Numeric value'), ('text', 'Text input')], default='checkbox', max_length=20, verbose_name='option type')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost (or discount if negative) for this option', max_digits=10, verbose_name='price adjustment')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service option',
                'verbose_name_plural': 'service options',
                'ordering': ['service', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='choice name')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost (or discount if negative) for this choice', max_digits=10, verbose_name='price adjustment')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='services.serviceoption', verbose_name='option')),
            ],
            options={
                'verbose_name': 'option choice',
                'verbose_name_plural': 'option choices',
                'ordering': ['option', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='variant name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost (or discount if negative) for this variant', max_digits=10, verbose_name='price adjustment')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service variant',
                'verbose_name_plural': 'service variants',
                'ordering': ['service', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='services_se_service_9fa833_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceoptionchoice',
            unique_together={('option', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='servicevariant',
            unique_together={('service', 'name')},
        ),
    ]
