# Generated by Django 5.0 on 2025-11-02 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 3, 3, 23, 10, 565283, tzinfo=datetime.timezone.utc
                ),
                verbose_name="delivery date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="special instructions"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 3, 3, 23, 36, 509012, tzinfo=datetime.timezone.utc
                ),
                verbose_name="pickup date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WASH_AND_FOLD", "Wash & Fold"),
                    ("WASH_AND_IRON", "Wash & Iron"),
                    ("DRY_CLEANING", "Dry Cleaning"),
                    ("IRONING", "Ironing Only"),
                ],
                default="WASH_AND_FOLD",
                max_length=20,
                verbose_name="service type",
            ),
        ),
    ]
