# Generated by Django 5.0 on 2025-11-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_date_order_notes_order_pickup_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
    ]
